blank_issues_enabled: true
contact_links:
  - name: Feature Request / Change Request
    url: https://aka.ms/sp-dev-uservoice
    about: Feature requests should be submitted to the SharePoint Dev UserVoice site.
  - name: SharePoint Developer Documentation
    url: https://docs.microsoft.com/sharepoint/dev
    about: All developer documentation for SharePoint can be found here.
  - name: SharePoint TechCommunity
    url: https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint
    about: Please submit non-developer questions/reports to the SharePoint TechCommunity site. This includes anything related to administrator, end-user, or user experience capabilities, questions, and errors.
